---
title: "individual2.Rmd"
author: "Elaine"
date: "3/26/2019"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)

offense <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
str(offense)

biography <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
str(biography)
```

?mutate_at
```{r}
defClean <- defense %>%
  mutate(Name = as.factor(Name),
         Opponent_Opponent = as.factor(Opponent_Opponent)) %>%
  mutate_if(is.character,as.numeric)
str(defClean)
print(str(defClean))

offClean <- offense %>%
  mutate(Name = as.factor(Name),
         Opponent_Opponent = as.factor(Opponent_Opponent)) %>%
  mutate_if(is.character,as.numeric, na.rm=TRUE)
str(offClean)
print(str(offClean))


bioClean <- biography %>%
  mutate(Name = as.factor(Name),
         Weight = as.numeric(Weight)) %>%
  separate(Height, c('feet', 'inches'), "-", convert=TRUE) %>%
  mutate(Height = (12*feet + inches)*2.54)
str(bioClean)
print(str(bioClean))
```

```{r}
#Part two: Tidying (1)
defClean <- defClean %>% gather(key=Statistic, value=Count, 3:11)
defClean

ggplot(defClean, aes(x=Count, fill=Statistic)) + geom_histogram(binwidth=0.7) +
  facet_wrap(~Statistic)

defClean <- defClean %>%
  spread(key=Statistic, value=Count)

library(ggplot2)

defClean2 <- defClean %>% gather(key=SoloTackles, value=Count, Tackles_Solo)

WVKS <- defClean2 %>%
  filter(Opponent_Opponent %in% c('West Virginia', 'Kansas State')) %>%
  select(Name, Opponent_Opponent, SoloTackles, Count) %>%
  spread(key=Opponent_Opponent, value=Count)

ggplot(WVKS, aes(x=`West Virginia`, y=`Kansas State`)) + geom_point(na.rm=TRUE) + xlab('West Virgina: Solo Tackles') + ylab('Kansas State: Solo Tackles')

```

```{r}
#Part two: Tidying(2)
#1. 
bioClean
bio1 <- bioClean %>%
  separate(Hometown,
           into=c('City', 'State'),
           sep=', ', convert = TRUE)
bioStates<- table(bio1$State)
print(bioStates)
```

```{r}
str(bio1)
str(offClean)
bio_offJoin<- inner_join(offClean, bio1, by = "Name")
playerHome <- bio_offJoin %>% distinct(Name, City, State)
print(playerHome)

ggplot(bio_offJoin, aes(x= Weight, y= Receiving_YDS, color= Name)) +
  geom_point(na.rm = TRUE)
```